### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1336-1339: surrogates not allowed

### ISSUE THREAD

**Issue by Lehirt** [flaribbit/paper-translator#3]
正在提取文本
skipping references
正在分割文本
正在翻译 1/8
正在翻译 2/8
正在翻译 3/8
正在翻译 4/8
Traceback (most recent call last):
  File "C:\Users\12574\Desktop\paper\paper-translator\main.py", line 90, in <module>
    main()
  File "C:\Users\12574\Desktop\paper\paper-translator\main.py", line 77, in main
    r = baidu_translator(text)
  File "C:\Users\12574\Desktop\paper\paper-translator\translator.py", line 19, in baidu_translator
    sign = make_md5(appid + query + str(salt) + appkey)
  File "C:\Users\12574\Desktop\paper\paper-translator\translator.py", line 11, in make_md5
    return hashlib.md5(s.encode(encoding)).hexdigest()
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1336-1339: surrogates not allowed

**Comment by flaribbit** [comment]
修了 但感觉这bug有点离谱（）

**Comment by Lehirt** [comment]
😂，又有新的问题，附测试PDF




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flaribbit/paper-translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flaribbit/paper-translator] UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1336-1339: surrogates not allowed (Issue #3)





 
修了 但感觉这bug有点离谱（）

**Comment by flaribbit** [comment]
邮件里贴附件似乎没用 网页端和邮件提醒都没看到

**Comment by Lehirt** [comment]
[Uploading TSP_CSSE_40728.pdf…]()

**Comment by flaribbit** [comment]
感谢反馈，查到原因了，有软件在导出pdf的公式里下毒

![UG{UVABO5I5{65BNVW2Q6BL](https://user-images.githubusercontent.com/24885181/169695214-cc390d72-3c71-40c4-b35c-e45709cea0d0.png)

已忽略这种公式

**Comment by Lehirt** [comment]
已解决~
